[build-system]
requires = [
    "setuptools >= 48",
    "setuptools_scm[toml] >= 4, <6",
    "wheel >= 0.29.0"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/tidy_models/version.py"
